project:
  type: book
  output-dir: _book
  resources:
    - data/
    - favicon/

book:
  title: "R for Computational Social Science"
  author: "Your Name"
  date: today
  date-format: "YYYY"
  repo-url: https://github.com/vanatteveldt/r4css
  repo-actions: [edit, issue]
  favicon: favicon/favicon.ico
  chapters:
    - index.qmd
    - part: "Data Analysis with Tidyverse"
      chapters:
        - chapters/02-funwithr.qmd
        - chapters/03-tidyverse.qmd
        - chapters/04-cleaning.qmd
        - chapters/05-transforming.qmd
        - chapters/06-visualizing.qmd
        - chapters/07-reshaping.qmd
        - chapters/08-customizing.qmd
    - part: "Text and Image Analysis"
      chapters:
        - chapters/09-stringr.qmd
        - chapters/10-scraping.qmd
        - chapters/11-tidytext.qmd
        - chapters/12-llms.qmd
        - chapters/13-images.qmd
    - part: "Machine Learning"
      chapters:
        - chapters/14-tidymodels.qmd
        - chapters/15-textclassification.qmd
        - chapters/16-dimensionality.qmd
        - chapters/17-torch.qmd
    - part: "Programming Concepts"
      chapters:
        - chapters/18-flowcontrol.qmd
        - chapters/19-datastructures.qmd
        - chapters/20-software.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  live-html:
    theme:
      light:
        - flatly
        - style.scss
      dark:
        - darkly
        - style.scss
        - style-dark.scss
    fontsize: 0.9em
    toc: true
    number-sections: true
    number-depth: 2

engine: knitr

execute:
  echo: true
  warning: false
  message: false
